version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "America/New_York"
    commit-message:
      prefix: "[github-actions] "      
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:30"
      timezone: "America/New_York"
    versioning-strategy: increase
    open-pull-requests-limit: 20
    insecure-external-code-execution: deny
    commit-message:
      prefix: "[bundler] "      
